### ISSUE TITLE
Fix JavaDocs for Java 8

### ISSUE THREAD

**Issue by logological** [dkpro/dkpro-wsd#77]
Java 8 uses much more strict checking for the syntax and semantics of the JavaDocs.  As a result the Maven JavaDoc plugin now reports errors.  Our JavaDocs need to be brought into compliance with the stricter Java 8 standards.

**Comment by logological** [comment]
Some progress has been made towards this issue, though adding descriptions for all the @param and @throws annotations will be a lot of effort.  For now we'll keep the Java target at 1.7.

**Comment by chmeyer** [comment]
I faced the same problem for dkpro-statistics. In case you want to switch to Java 8 without fixing all these "errors" immediately, you can add some pom magic: see https://github.com/dkpro/dkpro-statistics/blob/master/pom.xml (section about maven-javadoc-plugin).
